// Generates docs/spec/LEGACY_INDEX.md: every v12 top-level definition, the
// lines it occupies, the section it belongs to, and the module that will own
// it after the port. A session porting a system reads this instead of the
// 6,283-line file.

import { readFileSync, writeFileSync } from 'node:fs';
import { LEGACY_PATH } from '../legacy/legacy-game.ts';

/** v12 section header -> the package module that will own it. */
const SECTION_TARGETS: ReadonlyArray<readonly [RegExp, string]> = [
  [/helpers & data/i, 'core/util + content/tuning'],
  [/RUN_SCALE/i, 'content/tuning'],
  [/TUNING OBJECT/i, 'content/tuning'],
  [/audio/i, 'app/audio (rewritten, not ported)'],
  [/run recorder/i, 'harness/recorder'],
  [/kit-draft/i, 'core/state + content/kit'],
  [/food storage/i, 'core/systems/food'],
  [/worry ledger/i, 'core/systems/psyche/worry'],
  [/person layer/i, 'core/systems/psyche/person'],
  [/medical arcs/i, 'core/systems/medical'],
  [/time, cost & injury/i, 'core/systems/cost'],
  [/resolve/i, 'core/systems/psyche/resolve'],
  [/director/i, 'core/systems/psyche/director'],
  [/personal threads/i, 'core/systems/threads'],
  [/travel & signs/i, 'core/systems/travel'],
  [/actions: woods/i, 'core/commands/woods'],
  [/actions: shore/i, 'core/commands/shore'],
  [/actions: camp/i, 'core/commands/camp'],
  [/night \/ new day/i, 'core/pipelines/night + core/pipelines/dawn'],
  [/interior/i, 'core/systems/narrative + content/voice'],
  [/modals & endings/i, 'core/systems/endings + app/ui'],
  [/render/i, 'app/ui (rewritten, not ported)'],
  [/scene/i, 'app/world (rewritten, not ported)'],
  [/temperament tags/i, 'core/systems/psyche/tags'],
  [/modifier row/i, 'app/ui'],
  [/morale zero/i, 'core/systems/psyche/breakdown'],
  [/card engine/i, 'core/systems/cards + content/cards'],
  [/break sequence/i, 'core/systems/medical/break'],
  [/ending sequences/i, 'core/systems/endings + app/ui'],
];

interface Entry {
  kind: 'function' | 'const' | 'let';
  name: string;
  line: number;
  endLine: number;
}

interface Section {
  title: string;
  line: number;
  target: string;
  entries: Entry[];
}

export function buildLegacyIndex(html: string): Section[] {
  const lines = html.split('\n');
  const sections: Section[] = [];
  const definition = /^(function\s+([A-Za-z_$][\w$]*)|const\s+([A-Za-z_$][\w$]*)|let\s+([A-Za-z_$][\w$]*))\b/;

  lines.forEach((text, index) => {
    const header = /^\/\/ ={5,}\s*(.*?)\s*={5,}\s*$/.exec(text);
    if (header) {
      const title = header[1] ?? '';
      const target = SECTION_TARGETS.find(([pattern]) => pattern.test(title))?.[1] ?? 'unassigned';
      sections.push({ title, line: index + 1, target, entries: [] });
      return;
    }
    const match = definition.exec(text);
    if (!match || sections.length === 0) return;
    const name = match[2] ?? match[3] ?? match[4] ?? '';
    const kind = match[1]?.startsWith('function') ? 'function' : match[1]?.startsWith('const') ? 'const' : 'let';
    sections.at(-1)!.entries.push({ kind, name, line: index + 1, endLine: index + 1 });
  });

  // A definition runs until the next one, or the end of its section.
  sections.forEach((section, sectionIndex) => {
    const sectionEnd = sections[sectionIndex + 1]?.line ?? lines.length;
    section.entries.forEach((entry, entryIndex) => {
      entry.endLine = (section.entries[entryIndex + 1]?.line ?? sectionEnd) - 1;
    });
  });
  return sections;
}

export function renderLegacyIndex(sections: Section[]): string {
  const total = sections.reduce((sum, section) => sum + section.entries.length, 0);
  const out: string[] = [
    '# Legacy index',
    '',
    '`legacy/tap-out-v12.html` function by function: where each definition lives and which',
    'module owns it after the port. Generated by `npm run legacy:index`; do not edit by hand.',
    '',
    `${sections.length} sections, ${total} top-level definitions.`,
    '',
    '| Section | Lines | Target |',
    '|---|---|---|',
    ...sections.map(
      (section) =>
        `| ${section.title} | ${section.line}–${section.entries.at(-1)?.endLine ?? section.line} | \`${section.target}\` |`,
    ),
    '',
  ];
  for (const section of sections) {
    out.push(`## ${section.title}`, '', `Target: \`${section.target}\``, '', '| Definition | Lines |', '|---|---|');
    for (const entry of section.entries) {
      const range = entry.line === entry.endLine ? `${entry.line}` : `${entry.line}–${entry.endLine}`;
      out.push(`| \`${entry.name}\`${entry.kind === 'function' ? '()' : ''} | ${range} |`);
    }
    out.push('');
  }
  return out.join('\n');
}

export function writeLegacyIndex(path: string): number {
  const sections = buildLegacyIndex(readFileSync(LEGACY_PATH, 'utf8'));
  writeFileSync(path, renderLegacyIndex(sections));
  return sections.reduce((sum, section) => sum + section.entries.length, 0);
}
